### ISSUE TITLE
Modernize nginx reverse proxy

### ISSUE THREAD

**Issue by jonathansick** [lsst-sqre/ltd-keeper#24]
Currently the Kubernetes Deployment is still using the `lsstsqre/nginx-python:k8s` Docker image as the Nginx reverse proxy (from https://github.com/lsst-sqre/nginx-python-docker/blob/master/k8s/Dockerfile).

```yaml
        - name: nginx
          imagePullPolicy: "Always"
          image: "lsstsqre/nginx-python:k8s"
          ports:
            # from keeper-service
            - name: keeper-nginx
              containerPort: 8080
```

Probably we should be using a new Docker image, particularly one that's actively supported.

Alternatively, do we really need this reverse proxy since we've got Ingress on the front end and uwsgi running each application?
